name: mapfile_converter
resolution: workspace
description: A command-line application to convert pbf or osm files to mapfiles or osm files.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:

  # for argument parsing
  args: ^2.7.0

  fixnum: ^1.1.1

  # For logging to console
  # BSD License
  logging: ^1.3.0

  # Workspace
  mapsforge_flutter_core: ^1.0.0

  # Workspace
  mapsforge_flutter_mapfile: ^1.0.0

  # Workspace
  mapsforge_flutter_rendertheme: ^1.0.0

  # for pbf format
  protobuf: ^4.2.0

  # MIT License
  # for reading and writing osm files
  # compatibility problems with flutter_svg
  xml: ^6.5.0

dev_dependencies:

  lints: ^6.0.0

  test: ^1.26.2

  # test dart executable in isolate
  process_run: ^1.2.4
