name: mapfile_converter
resolution: workspace
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:

  # for argument parsing
  args: ^2.7.0

  # Workspace
  dart_common: ^1.0.0

  # Workspace
  dart_isolate: ^1.0.0

  # Workspace
  dart_mapfile: ^1.0.0

  # Workspace
  dart_rendertheme: ^1.0.0

  # For logging to console
  # BSD License
  logging: ^1.3.0

  # for pbf format
  protobuf: ^4.1.0

  # Workspace
  task_queue: ^1.0.0

  # MIT License
  # for reading and writing osm files
  xml: ^6.6.1

dev_dependencies:

  lints: ^6.0.0

  test: ^1.26.2

  # test dart executable in isolate
  process_run: ^1.2.4
