name: mapsforge_assets
resolution: workspace
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

  lints: ^6.0.0

  # BSD-3
  test: ^1.26.2

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

assets:
  - lib/assets/
  - lib/assets/patterns/access-destination.png