name: dart_isolate
resolution: workspace
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  #path: ^1.9.0

  rxdart: ^0.28.0

dev_dependencies:
  lints: ^6.0.0

  test: ^1.26.2
