name: mapfile_converter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:

  # for argument parsing
  args: ^2.7.0

  isolate_task_queue: ^1.0.1

  # For logging to console
  # BSD License
  logging: ^1.3.0

  mapsforge_flutter:
   path: ../

  grpc: ^4.1.0

  protobuf: ^4.1.0

  # MIT License
  # for reading and writing osm files
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15

  lints: ^6.0.0

  test: ^1.25.15

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true