name: mapfile_converter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:

  # for argument parsing
  args: ^2.7.0

  # For logging to console
  # BSD License
  logging: ^1.3.0

  mapsforge_flutter:
   path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.1.1

  test: ^1.25.15

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true