name: dart_rendertheme
resolution: workspace
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:

  # Enhancement for collections
  collection: ^1.19.1

  # Workspace
  dart_common: ^1.0.0

  # Workspace
  ecache: ^2.0.10

  # MIT License
  # for reading the rendertheme xml file
  # compatibility problems with flutter_svg
  xml: ^6.5.0


dev_dependencies:

  lints: ^6.0.0

  # BSD-3
  test: ^1.26.2