name: dart_common
resolution: workspace
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:

  dart_isolate: ^1.0.0

  ecache: ^2.0.9

  task_queue: ^1.0.0

dev_dependencies:
  lints: ^6.0.0

  test: ^1.26.2
