name: mapsforge_flutter_core
resolution: workspace
description: Common files for mapsforge in dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:

  ecache: ^2.0.13

  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0

  test: ^1.26.2
