name: mapsforge_flutter_core
resolution: workspace
description: Common files for mapsforge in dart.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:

  ecache: ^2.1.1

  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0

  test: ^1.26.2
